project_id = "wwtkdgyywnaijxkdkguo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[functions.ai-triage]
verify_jwt = false

[functions.ai-vision-analysis]
verify_jwt = false

[functions.medical-report]
verify_jwt = false

[functions.ai-live-triage]
verify_jwt = false

[functions.ai-live-vision]
verify_jwt = false

[functions.platform-stats]
verify_jwt = false
