services:
  - type: web
    name: apnedoctors
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    healthCheckPath: /
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: NODE_ENV
        value: production
